### ISSUE TITLE
Docker in Docker using private registry

### ISSUE THREAD

**Issue by henthu** [JetBrains/teamcity-docker-samples#9]
Hello,

I have put the variable to start docker to "start" and configured the build to push to a private company registry with valid certificate.

The problem is I have an error  "x509: certificate signed by unknown authority"

I tried to mount a volume /etc/docker/certs.d/<mydomain.com>/ca.crt but did not solve the problem.

is there any other variable to give the tls certificate to the docker inside the agent?

Thank you for your help

**Comment by kir** [comment]
Hello,

  I'm not quite proficient with configuring TLS certificates for Docker, but probably some details on these pages could help: 
   https://www.labkey.org/Documentation/wiki-page.view?name=dockerTLS#change
   https://tech.paulcz.net/blog/secure-docker-with-tls/ 
   
  Hope this helps,
